#!/bin/bash

source ./hack/scripts/common

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=$(git tag -l --contains HEAD | head -n 1)

if [[ -z "$DIRTY" && -n "$COMMIT" ]]; then
    VERSION=$COMMIT
    export REFUNC_VERSION=${VERSION}
    export LOADER_VERSION=${VERSION}
    export SIDECAR_VERSION=${VERSION}
    export CREDSYNCER_VERSION=${VERSION}
else
    _DEPS_VERSION=$(
        echo \
        $(get_version $(find pkg -type f -name '*.go')) \
        $(get_version cmd/refunc/*.go) \
        $(get_version cmd/controller/*.go) \
        $(get_version cmd/play/*.go) \
        $(get_version cmd/triggers/*.go) | my_sha1sum | cut -c 1-8
    )
    export REFUNC_VERSION=${_DEPS_VERSION}${DIRTY}
    export LOADER_VERSION=$(echo $(get_version $(find pkg -type f -name '*.go') cmd/loader/*.go package/Dockerfile) | my_sha1sum | cut -c 1-8)${DIRTY}
    export SIDECAR_VERSION=$(echo $(get_version $(find pkg -type f -name '*.go') cmd/sidecar/*.go package/Dockerfile) | my_sha1sum | cut -c 1-8)${DIRTY}
    export CREDSYNCER_VERSION=$(echo $(get_version $(find pkg -type f -name '*.go') cmd/credsyncer/*.go package/Dockerfile) | my_sha1sum | cut -c 1-8)${DIRTY}
fi

IMAGE_REPO=${IMAGE_REPO:-refunc}

export REGISTRY_PREFIX="${IMAGE_REPO}/${IMAGE_PREFIX}"

export REFUNC_IMAGE="${REGISTRY_PREFIX}refunc:${REFUNC_VERSION}"
export LOADER_IMAGE="${REGISTRY_PREFIX}loader:${LOADER_VERSION}"
export SIDECAR_IMAGE="${REGISTRY_PREFIX}sidecar:${SIDECAR_VERSION}"
export CREDSYNCER_IMAGE="${REGISTRY_PREFIX}credsyncer:${CREDSYNCER_VERSION}"
